version: '3.3'
services:
    ic-webapp:
        container_name: ic-webapp
        ports:
            - "8080:8080"
        environment:
            - "ODOO_URL=http://${HOST_IP}:8069/"
            - "PGADMIN_URL=http://${HOST_IP}:5050/"
        image: 'julios2/ic-webapp:1.0'
        networks:
            - ic_webapp_network

networks:
    ic_webapp_network:
      driver: bridge