version: '3.3'
services:
  ic-webapp:
    depends_on:
      - odoo_web
      - pgadmin
    container_name: ic-webapp
    ports:
      - "8080:8080"
    environment:
      - "ODOO_URL=http://${HOST_IP}:8069/"
      - "PGADMIN_URL=http://${HOST_IP}:5050/"
    image: 'julios2/ic-webapp:1.0'
    networks:
      - ic-group_network

  odoo_web:
    container_name: odoo_web
    image: odoo:14.0
    ports:
      - "8069:8069"
    depends_on:
      - postgresql
    volumes:
      - odoo-web-data:/var/lib/odoo
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
      - HOST=postgresql
      - USER=my_user
    secrets:
      - postgresql_password
    networks:
      - ic-group_network

  pgadmin:
    container_name: pgadmin
    depends_on:
      - postgresql
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=landojules535@yahoo.fr
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
    secrets:
      - pgadmin_password
    image: 'dpage/pgadmin4:latest'
    volumes:
      - 'pgadmin-data:/usr/local/pgsql-13'
      - ${PWD}/configs/servers.json:/pgadmin4/servers.json
    networks:
      - ic-group_network

  postgresql:
    container_name: postgresql
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=my_user
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    networks:
      - ic-group_network

volumes:
  odoo-web-data:
  postgres-data:
  pgadmin-data:

secrets:
  postgresql_password:
    file: secrets/postgres_pass
  pgadmin_password:
    file: secrets/pgadmin_pass

networks:
  ic-group_network:
    driver: bridge