version: '3.3'
services:
    pgadmin:
        container_name: pgadmin
        ports:
            - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=landojules535@yahoo.fr
            - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
        image: 'dpage/pgadmin4:latest'
        secrets:
            -   pgadmin_password
        volumes:
            -   pgadmin-data:/usr/local/pgsql-13
        networks:
            - pgadmin_network

volumes:
    pgadmin-data:

networks:
    pgadmin_network:
      driver: bridge

secrets:
  pgadmin_password:
    file: secrets/pgadmin_pass