version: '3.3'
services:
  odoo_web:
    container_name: odoo_web
    image: odoo:14.0
    depends_on:
      - postgresql
    ports:
      - "80:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
      - HOST=postgresql
      - USER=odoo_user
    secrets:
      - postgresql_password
    networks:
      - odoo_network
  postgresql:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo_user
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    networks:
      - odoo_network
volumes:
  odoo-web-data:
  postgres-data:

secrets:
  postgresql_password:
    file: secrets/postgres_pass

networks:
  odoo_network:
    driver: bridge