apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-web
  namespace: icgroup
  labels:
    app: odoo-web
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo-web
      env: prod
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odoo-web
        env: prod
    spec:
      containers:
      - name: odoo-web
        image: odoo:14.0
        ports:
          - containerPort: 8069
        env:
          - name: HOST
            value: service-e
          - name: USER
            value: odoo
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secrets
                key: postgres_password
        volumeMounts:
        - mountPath: /var/lib/odoo
          name: odoo-web-datas

      volumes:
      - name: odoo-web-datas
        hostPath:
          path: /odoo-web-data
          type: Directory