---
- hosts: prod:dev
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - ../roles/commun/main.yml
    - ../secrets/credentials.yml
  roles:
    - role: ../roles/pgadmin_role
