apiVersion: v1
kind: Pod
metadata:
  name: bdd-odoo
  namespace: icgroup
  labels:
    app: bdd-odoo
    env: prod
spec:
  containers:
  - name: postgres-db
    image: postgres:13
    ports:
      - containerPort: 5432
    env:
     - name: POSTGRES_DB
       value: postgres
     - name: POSTGRES_USER
       value: odoo
     - name: POSTGRES_PASSWORD
       valueFrom:
         secretKeyRef:
           name: pg-secrets
           key: postgres_password
     - name: PGDATA
       value: /var/lib/postgresql/data/pgdata
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: postgres-datas

  volumes:
    - name: postgres-datas
      hostPath:
        path: /k8s_data/postgres-data
        type: Directory
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bdd-odoo
    env: prod
  name: service-e
  namespace: icgroup
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: bdd-odoo
  type: ClusterIP
status:
  loadBalancer: {}