apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: odoo-web
    env: prod
  name: service-c
  namespace: icgroup
spec:
  ports:
  - nodePort: 30011
    port: 8069
    protocol: TCP
    targetPort: 8069
  selector:
    app: odoo-web
  type: NodePort
status:
  loadBalancer: {}