apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pgadmin
    env: prod
  name: service-g
  namespace: icgroup
spec:
  ports:
  - nodePort: 30012
    port: 5050  # app server port
    protocol: TCP
    targetPort: 80  # pgadmin listener port
  selector:
    app: pgadmin
  type: NodePort
status:
  loadBalancer: {}